# Aim to have fast builds
# TODO: Maybe don't build the files into seperate folders and copy them after that anyway.

language: php

php:
  - 7.0

git:
  depth: 1
  submodules: false

if: branch IS master
if: tag IS blank

branches:
  only:
    master

# Simultaneous builds for common and uncommon resolutions
env:
  matrix:
    - buildType=Common
    - buildType=Uncommon
  global:
    - secure: "X0PrKXLjW6r8e0zT7+SshhP7uaW/5EW2BJPCc/oRIWX6eC4QLXv0lQBstIZ6vChAvgYv2K1CcBlWHrQarTlHqmkYnfHAfOFK//qURFUfuyTkKcKU/aCYvm4op0jPGw8+wbOkxwfnbvOaa0E7oBv4GCXVPYCU3nm7E1H2XHgcfJukaEhpvFfHaNohoh1ygVt65G1WIoYwUIFh/0XXgP6RVBDCAU+QYaNopK5co2O40vhjtg2f0la4zMsunMEY5oXNMaM/oRAvGBaXJ3KUTgSb0+uRlEM/XxOYRyfmG6fjVXYbwL6j+kNCLsZklCfN98AAvbysCebQWhI46vJcPa/Ji/ImMeAns17fBlHMn+PI0MIBbPkMztEkenXW3Yv1BquBHElhB758Fd1Zt9KdA5H5JC6WfuRBd+QBwlzOBxOrVfmaI3uOmy3cEvQZgckPGN+7SdSDyrw/+ukM+Ks775qaZ/bw3eQyMx6DpfATa6pVzK0AWj4Xlm4IufaOFI/hy2gH60hV+3KuYXeSJOq4gXYbtJcruAbHK5YOeEmAEsVCpz+RKSuAWWvcPktoyLTOjbGTM89Yf3jFgZOFi4HNCt7K67/bDnflsHj04X/pDm3gQ0XhxQx1Sj1j0IG1XLh+k37uL2FZusBbd+8kI1SkMED5aVWTp1WmbJN+dJXZMWJxJPc=" # GITHUB_TOKEN

matrix:
  fast_finish: true

# === Build steps ===

# No dependencies
install: npm install -g github-release-cli@0.4.1

# No need to debug the PHP code. Keeping this enabled slows down execution.
before_script:
  - phpenv config-rm xdebug.ini

script: ./build.sh

after_success:
  # Create zip file
  - mkdir build
  - mv $TRAVIS_BUILD_DIR/Enhancement/* build
  - mv $TRAVIS_BUILD_DIR/Enthusiast/* build
  - mv $TRAVIS_BUILD_DIR/Modifications/* build
  - mv $TRAVIS_BUILD_DIR/Performance/* build
  - mv $TRAVIS_BUILD_DIR/Quality/* build
  - mv $TRAVIS_BUILD_DIR/Workaround/* build
  - cd build
  - zip -o -9 -r -q "../graphicPacks$buildType""_$TRAVIS_BUILD_NUMBER"".zip" ./*
  - cd ..
  # Create github release
  # Remove previous Common asset from release if making the final release with both Common and Uncommon as we need to upload it in a different order to maintain compatibility with existing tools.
  - |
    if [ "$buildType" = "Uncommon" ]; then
    wget "https://github.com/slashiee/cemu_graphic_packs/releases/download/Travis$TRAVIS_BUILD_NUMBER/graphicPacksCommon_$TRAVIS_BUILD_NUMBER.zip";
    github-release delete --owner=slashiee --repo=cemu_graphic_packs --name="Graphic Packs: version $TRAVIS_BUILD_NUMBER" --tag="Travis$TRAVIS_BUILD_NUMBER" "graphicPacksCommon_$TRAVIS_BUILD_NUMBER"".zip";
    fi
  # Upload the release.
  # The Common build will have the prerelease tag (the Github API skips prereleases if you use the "latest" tag which improves cases where the Common build isn't completed yet).
  # The Uncommon build will upload both the Common (from the step above) and Uncommon in a specific order. It also removes the prerelease tag.
  - |
    github-release upload \
      --owner=slashiee \
      --repo=cemu_graphic_packs \
      --tag="Travis$TRAVIS_BUILD_NUMBER" \
      --name="Graphic Packs: version $TRAVIS_BUILD_NUMBER" \
      --body="$(git log -1 --format='Commited at %ci by **%cn** in commit %h%n### %s%n```%n%b%n```%n') $(if [ '$buildType' = 'Common' ]; then echo 'This is a prerelease with only the common resolutions.'; fi)" \
      $([ "$buildType" = "Common" ] && echo "--prerelease=true" || echo "--prerelease=false") \
      "graphicPacks$buildType""_$TRAVIS_BUILD_NUMBER"".zip" \
      $([ "$buildType" = "Uncommon" ] && echo "graphicPacksCommon_$TRAVIS_BUILD_NUMBER"".zip" || echo "")
